package verbs

import (
	"context"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"unicode"

	"golang.org/x/tools/imports"

	"ratchet/internal/db"
)

// apiCheckTestFilename is the mechanically-owned compile-time signature-check
// file. Its content is fully regenerated by writeAPICheckTest from the
// SURVEY_SPEC manifest — never hand-written — so it's named to make that
// obvious to both humans and models: nothing should ever add behavioral
// tests or other logic here.
const apiCheckTestFilename = "do_not_use_this_test.go"

// scaffoldGoProject materializes a Go project from SURVEY_SPEC declaration-only
// files. For each source file it computes required imports from the declaration
// text and writes a complete syntactically valid .go file. It then generates
// go.mod (using the host Go runtime version) and apiCheckTestFilename (existence
// checks for all exported symbols).
func scaffoldGoProject(pkg, module, folderPath string, files []SurveyManifestFile) error {
	goVer := goRuntimeVersion()

	for _, f := range files {
		if !strings.HasSuffix(f.Path, ".go") || filepath.Base(f.Path) == apiCheckTestFilename {
			continue
		}
		content := buildGoFile(pkg, f.Declarations)
		fullPath := filepath.Join(folderPath, f.Path)
		if err := os.MkdirAll(filepath.Dir(fullPath), 0755); err != nil {
			return fmt.Errorf("mkdir for %s: %w", f.Path, err)
		}
		if err := os.WriteFile(fullPath, []byte(content), 0644); err != nil {
			return fmt.Errorf("write %s: %w", f.Path, err)
		}
	}

	goMod := goModContent(module, goVer)
	if err := os.WriteFile(filepath.Join(folderPath, "go.mod"), []byte(goMod), 0644); err != nil {
		return fmt.Errorf("write go.mod: %w", err)
	}

	if err := writeAPICheckTest(pkg, folderPath, files); err != nil {
		return fmt.Errorf("write %s: %w", apiCheckTestFilename, err)
	}

	return nil
}

// WriteScaffoldStubs resets all non-test output files to a clean baseline,
// always overwriting existing content. Used by rewind-bead to restore the
// VERIFY_MANIFEST baseline state before re-running EXECUTE_BEAD.
//
// A file's baseline depends on whether SURVEY_SPEC scaffolded it: files
// declared in the manifest (all .go source files) are reset to their
// mechanical scaffold stub. Files NOT in the manifest (e.g. a non-Go file
// like a template that a bead wrote directly, since SURVEY only scaffolds
// .go files) have no stub to reset to — they are deleted instead, the same
// treatment _test.go files already get, so every output file genuinely
// returns to a clean baseline rather than silently keeping stale content.
// Returns the files actually stubbed and the files actually deleted, so
// callers can report what really happened instead of assuming success.
func WriteScaffoldStubs(ctx context.Context, d *db.DB, projectID int64, folderPath string, outputFiles []string) (stubbed, deleted []string, err error) {
	manifest, err := latestSurveyManifest(ctx, d, projectID)
	if err != nil {
		return nil, nil, fmt.Errorf("load survey manifest: %w", err)
	}
	declByPath := make(map[string]string, len(manifest.Files))
	for _, mf := range manifest.Files {
		declByPath[mf.Path] = mf.Declarations
	}
	for _, f := range outputFiles {
		if strings.HasSuffix(f, "_test.go") {
			continue
		}
		if f == "go.mod" {
			// go.mod is never one of the manifest's per-file declarations —
			// scaffoldGoProject (VERIFY_MANIFEST) writes it mechanically from
			// the module name + host Go version, not from a manifest entry.
			// It still has a deterministic baseline; regenerate it the same
			// way instead of falling into the "no baseline, delete" branch
			// below, which would leave the package permanently uncompilable
			// (every downstream compile check needs go.mod to exist).
			goMod := goModContent(manifest.Module, goRuntimeVersion())
			if err := os.WriteFile(filepath.Join(folderPath, f), []byte(goMod), 0644); err != nil {
				return stubbed, deleted, fmt.Errorf("write scaffold go.mod: %w", err)
			}
			stubbed = append(stubbed, f)
			continue
		}
		decl, ok := declByPath[f]
		if !ok {
			path := filepath.Join(folderPath, f)
			if rmErr := os.Remove(path); rmErr != nil && !os.IsNotExist(rmErr) {
				return stubbed, deleted, fmt.Errorf("delete non-manifest output file %s: %w", f, rmErr)
			}
			deleted = append(deleted, f)
			continue
		}
		content := buildGoFile(manifest.Package, decl)
		if err := os.WriteFile(filepath.Join(folderPath, f), []byte(content), 0644); err != nil {
			return stubbed, deleted, fmt.Errorf("write scaffold %s: %w", f, err)
		}
		stubbed = append(stubbed, f)
	}
	return stubbed, deleted, nil
}

// restoreMissingScaffolds writes scaffold stubs only for non-test output files
// that are absent from disk. Called at the start of REFINE_TESTS_WRITE so the
// compile step succeeds even when impl files are missing.
func restoreMissingScaffolds(ctx context.Context, d *db.DB, projectID int64, folderPath string, outputFiles []string) error {
	var missing []string
	for _, f := range outputFiles {
		if strings.HasSuffix(f, "_test.go") {
			continue
		}
		if _, err := os.Stat(filepath.Join(folderPath, f)); os.IsNotExist(err) {
			missing = append(missing, f)
		}
	}
	if len(missing) == 0 {
		return nil
	}
	_, _, err := WriteScaffoldStubs(ctx, d, projectID, folderPath, missing)
	return err
}

// buildGoFile prepends the package declaration and resolves imports for the
// declaration text via goimports, which consults the real stdlib package
// index rather than a hand-maintained name table. If import resolution or
// gofmt fails (the model produced a syntax error), the unformatted source is
// returned so the compile check can surface a precise error message.
func buildGoFile(pkg, declarations string) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "package %s\n\n", pkg)
	sb.WriteString(declarations)
	src := sb.String()

	formatted, err := imports.Process("", []byte(src), nil)
	if err != nil {
		return src
	}
	return string(formatted)
}

// writeAPICheckTest generates apiCheckTestFilename containing one "var _ = X"
// assertion per exported function and exported package-level variable or
// constant across all manifest files. For package main these reference
// symbols directly (no import needed since we're in the same package).
func writeAPICheckTest(pkg, folderPath string, files []SurveyManifestFile) error {
	var assertions []string
	for _, f := range files {
		if !strings.HasSuffix(f.Path, ".go") || strings.HasSuffix(f.Path, "_test.go") {
			continue
		}
		fset := token.NewFileSet()
		astFile, err := parser.ParseFile(fset, "", "package p\n\n"+f.Declarations, 0)
		if err != nil {
			continue
		}
		assertions = append(assertions, exportedAssertions(astFile)...)
	}

	var sb strings.Builder
	fmt.Fprintf(&sb, "package %s\n\n", pkg)
	if len(assertions) > 0 {
		sb.WriteString("var (\n")
		for _, a := range assertions {
			fmt.Fprintf(&sb, "\t_ = %s\n", a)
		}
		sb.WriteString(")\n")
	}

	return os.WriteFile(filepath.Join(folderPath, apiCheckTestFilename), []byte(sb.String()), 0644)
}

// exportedAssertions returns a right-hand side expression for "var _ = X" for
// each exported function and each exported package-level variable or constant
// in the file.
func exportedAssertions(f *ast.File) []string {
	var out []string
	for _, decl := range f.Decls {
		switch d := decl.(type) {
		case *ast.FuncDecl:
			if !isExportedIdent(d.Name.Name) {
				continue
			}
			if d.Recv != nil {
				if typName := receiverTypeName(d.Recv); typName != "" {
					out = append(out, fmt.Sprintf("(*%s).%s", typName, d.Name.Name))
				}
			} else {
				out = append(out, d.Name.Name)
			}

		case *ast.GenDecl:
			if d.Tok != token.VAR && d.Tok != token.CONST {
				continue
			}
			for _, spec := range d.Specs {
				vs, ok := spec.(*ast.ValueSpec)
				if !ok {
					continue
				}
				for _, name := range vs.Names {
					if isExportedIdent(name.Name) {
						out = append(out, name.Name)
					}
				}
			}
		}
	}
	return out
}

// receiverTypeName returns the base type name from a receiver field list,
// stripping any pointer star.
func receiverTypeName(recv *ast.FieldList) string {
	if recv == nil || len(recv.List) == 0 {
		return ""
	}
	switch t := recv.List[0].Type.(type) {
	case *ast.StarExpr:
		if id, ok := t.X.(*ast.Ident); ok {
			return id.Name
		}
	case *ast.Ident:
		return t.Name
	}
	return ""
}

// isExportedIdent reports whether name is an exported Go identifier.
func isExportedIdent(name string) bool {
	return name != "" && unicode.IsUpper(rune(name[0]))
}

// goModContent returns the content of a mechanically-generated go.mod for
// module at Go version goVer. Shared by scaffoldGoProject (initial scaffold,
// at VERIFY_MANIFEST) and WriteScaffoldStubs (rewind-bead's reset-to-baseline
// path) so the two never drift out of sync on what "the baseline go.mod"
// actually contains.
func goModContent(module, goVer string) string {
	return fmt.Sprintf("module %s\n\ngo %s\n", module, goVer)
}

// goRuntimeVersion returns the current Go version in "M.N" form (e.g. "1.24").
func goRuntimeVersion() string {
	v := strings.TrimPrefix(runtime.Version(), "go")
	parts := strings.SplitN(v, ".", 3)
	if len(parts) >= 2 {
		return parts[0] + "." + parts[1]
	}
	return v
}

// wipeGoProject removes all .go files, go.mod, and go.sum from folderPath.
// Errors are silently ignored — the next SURVEY attempt overwrites anyway.
func wipeGoProject(folderPath string) {
	_ = filepath.WalkDir(folderPath, func(path string, d os.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return nil
		}
		base := filepath.Base(path)
		if strings.HasSuffix(base, ".go") || base == "go.mod" || base == "go.sum" {
			_ = os.Remove(path)
		}
		return nil
	})
}