package verbs

import (
	"context"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"unicode"

	"ratchet/internal/db"
)

// stdlibPkgToImport maps unqualified package names to their standard library
// import paths. Used by inferImports to resolve package-qualified identifiers
// in declaration text (e.g. "http" → "net/http").
var stdlibPkgToImport = map[string]string{
	"atomic":   "sync/atomic",
	"base64":   "encoding/base64",
	"big":      "math/big",
	"bufio":    "bufio",
	"bytes":    "bytes",
	"cipher":   "crypto/cipher",
	"cmp":      "cmp",
	"context":  "context",
	"csv":      "encoding/csv",
	"errors":   "errors",
	"exec":     "os/exec",
	"flag":     "flag",
	"filepath": "path/filepath",
	"fmt":      "fmt",
	"gob":      "encoding/gob",
	"gzip":     "compress/gzip",
	"heap":     "container/heap",
	"hex":      "encoding/hex",
	"html":     "html",
	"http":     "net/http",
	"httptest": "net/http/httptest",
	"io":       "io",
	"iter":     "iter",
	"json":     "encoding/json",
	"list":     "container/list",
	"log":      "log",
	"maps":     "maps",
	"math":     "math",
	"mime":     "mime",
	"net":      "net",
	"netip":    "net/netip",
	"os":       "os",
	"path":     "path",
	"rand":     "math/rand",
	"regexp":   "regexp",
	"ring":     "container/ring",
	"runtime":  "runtime",
	"sha256":   "crypto/sha256",
	"signal":   "os/signal",
	"slices":   "slices",
	"slog":     "log/slog",
	"sort":     "sort",
	"strconv":  "strconv",
	"strings":  "strings",
	"sync":     "sync",
	"tar":      "archive/tar",
	"template": "html/template",
	"testing":  "testing",
	"time":     "time",
	"tls":      "crypto/tls",
	"unicode":  "unicode",
	"url":      "net/url",
	"utf8":     "unicode/utf8",
	"xml":      "encoding/xml",
	"zip":      "archive/zip",
	"zlib":     "compress/zlib",
}

// apiCheckTestFilename is the mechanically-owned compile-time signature-check
// file. Its content is fully regenerated by writeAPICheckTest from the
// SURVEY_SPEC manifest — never hand-written — so it's named to make that
// obvious to both humans and models: nothing should ever add behavioral
// tests or other logic here.
const apiCheckTestFilename = "do_not_use_this_test.go"

// scaffoldGoProject materializes a Go project from SURVEY_SPEC declaration-only
// files. For each source file it computes required imports from the declaration
// text and writes a complete syntactically valid .go file. It then generates
// go.mod (using the host Go runtime version) and apiCheckTestFilename (existence
// checks for all exported symbols).
func scaffoldGoProject(pkg, module, folderPath string, files []SurveyManifestFile) error {
	goVer := goRuntimeVersion()

	for _, f := range files {
		if !strings.HasSuffix(f.Path, ".go") || filepath.Base(f.Path) == apiCheckTestFilename {
			continue
		}
		content := buildGoFile(pkg, f.Declarations)
		fullPath := filepath.Join(folderPath, f.Path)
		if err := os.MkdirAll(filepath.Dir(fullPath), 0755); err != nil {
			return fmt.Errorf("mkdir for %s: %w", f.Path, err)
		}
		if err := os.WriteFile(fullPath, []byte(content), 0644); err != nil {
			return fmt.Errorf("write %s: %w", f.Path, err)
		}
	}

	goMod := fmt.Sprintf("module %s\n\ngo %s\n", module, goVer)
	if err := os.WriteFile(filepath.Join(folderPath, "go.mod"), []byte(goMod), 0644); err != nil {
		return fmt.Errorf("write go.mod: %w", err)
	}

	if err := writeAPICheckTest(pkg, folderPath, files); err != nil {
		return fmt.Errorf("write %s: %w", apiCheckTestFilename, err)
	}

	return nil
}

// WriteScaffoldStubs writes scaffold stub implementations for all non-test
// output files, always overwriting existing content. Used by rewind-bead to
// restore the VERIFY_MANIFEST baseline state before re-running EXECUTE_BEAD.
func WriteScaffoldStubs(ctx context.Context, d *db.DB, projectID int64, folderPath string, outputFiles []string) error {
	manifest, err := latestSurveyManifest(ctx, d, projectID)
	if err != nil {
		return fmt.Errorf("load survey manifest: %w", err)
	}
	needed := make(map[string]bool)
	for _, f := range outputFiles {
		if !strings.HasSuffix(f, "_test.go") {
			needed[f] = true
		}
	}
	for _, mf := range manifest.Files {
		if !needed[mf.Path] {
			continue
		}
		content := buildGoFile(manifest.Package, mf.Declarations)
		if err := os.WriteFile(filepath.Join(folderPath, mf.Path), []byte(content), 0644); err != nil {
			return fmt.Errorf("write scaffold %s: %w", mf.Path, err)
		}
	}
	return nil
}

// restoreMissingScaffolds writes scaffold stubs only for non-test output files
// that are absent from disk. Called at the start of REFINE_TESTS_WRITE so the
// compile step succeeds even when impl files are missing.
func restoreMissingScaffolds(ctx context.Context, d *db.DB, projectID int64, folderPath string, outputFiles []string) error {
	var missing []string
	for _, f := range outputFiles {
		if strings.HasSuffix(f, "_test.go") {
			continue
		}
		if _, err := os.Stat(filepath.Join(folderPath, f)); os.IsNotExist(err) {
			missing = append(missing, f)
		}
	}
	if len(missing) == 0 {
		return nil
	}
	return WriteScaffoldStubs(ctx, d, projectID, folderPath, missing)
}

// buildGoFile prepends the package declaration, infers imports from the
// declaration text, and formats the result. If gofmt fails (the model
// produced a syntax error), the unformatted source is returned so the
// compile check can surface a precise error message.
func buildGoFile(pkg, declarations string) string {
	imports := inferImports(declarations)

	var sb strings.Builder
	fmt.Fprintf(&sb, "package %s\n", pkg)
	if len(imports) > 0 {
		sb.WriteString("\nimport (\n")
		for _, imp := range imports {
			fmt.Fprintf(&sb, "\t%q\n", imp)
		}
		sb.WriteString(")\n")
	}
	sb.WriteString("\n")
	sb.WriteString(declarations)
	src := sb.String()

	formatted, err := format.Source([]byte(src))
	if err != nil {
		return src
	}
	return string(formatted)
}

// inferImports parses declaration text and returns sorted import paths for
// every package-qualified identifier (pkg.Symbol) that maps to a known stdlib
// package. Unknown qualifiers are silently skipped — the compile check will
// surface them with a precise error.
func inferImports(declarations string) []string {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "", "package p\n\n"+declarations, parser.ParseComments)
	if err != nil {
		return nil
	}

	seen := map[string]bool{}
	ast.Inspect(f, func(n ast.Node) bool {
		sel, ok := n.(*ast.SelectorExpr)
		if !ok {
			return true
		}
		id, ok := sel.X.(*ast.Ident)
		if !ok {
			return true
		}
		if imp, ok := stdlibPkgToImport[id.Name]; ok {
			seen[imp] = true
		}
		return true
	})

	paths := make([]string, 0, len(seen))
	for p := range seen {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	return paths
}

// writeAPICheckTest generates apiCheckTestFilename containing one "var _ = X"
// assertion per exported function and exported package-level variable across
// all manifest files. For package main these reference symbols directly (no
// import needed since we're in the same package).
func writeAPICheckTest(pkg, folderPath string, files []SurveyManifestFile) error {
	var assertions []string
	for _, f := range files {
		if !strings.HasSuffix(f.Path, ".go") || strings.HasSuffix(f.Path, "_test.go") {
			continue
		}
		fset := token.NewFileSet()
		astFile, err := parser.ParseFile(fset, "", "package p\n\n"+f.Declarations, 0)
		if err != nil {
			continue
		}
		assertions = append(assertions, exportedAssertions(astFile)...)
	}

	var sb strings.Builder
	fmt.Fprintf(&sb, "package %s\n\n", pkg)
	if len(assertions) > 0 {
		sb.WriteString("var (\n")
		for _, a := range assertions {
			fmt.Fprintf(&sb, "\t_ = %s\n", a)
		}
		sb.WriteString(")\n")
	}

	return os.WriteFile(filepath.Join(folderPath, apiCheckTestFilename), []byte(sb.String()), 0644)
}

// exportedAssertions returns a right-hand side expression for "var _ = X" for
// each exported function and each exported package-level variable in the file.
func exportedAssertions(f *ast.File) []string {
	var out []string
	for _, decl := range f.Decls {
		switch d := decl.(type) {
		case *ast.FuncDecl:
			if !isExportedIdent(d.Name.Name) {
				continue
			}
			if d.Recv != nil {
				if typName := receiverTypeName(d.Recv); typName != "" {
					out = append(out, fmt.Sprintf("(*%s).%s", typName, d.Name.Name))
				}
			} else {
				out = append(out, d.Name.Name)
			}

		case *ast.GenDecl:
			if d.Tok != token.VAR {
				continue
			}
			for _, spec := range d.Specs {
				vs, ok := spec.(*ast.ValueSpec)
				if !ok {
					continue
				}
				for _, name := range vs.Names {
					if isExportedIdent(name.Name) {
						out = append(out, name.Name)
					}
				}
			}
		}
	}
	return out
}

// receiverTypeName returns the base type name from a receiver field list,
// stripping any pointer star.
func receiverTypeName(recv *ast.FieldList) string {
	if recv == nil || len(recv.List) == 0 {
		return ""
	}
	switch t := recv.List[0].Type.(type) {
	case *ast.StarExpr:
		if id, ok := t.X.(*ast.Ident); ok {
			return id.Name
		}
	case *ast.Ident:
		return t.Name
	}
	return ""
}

// isExportedIdent reports whether name is an exported Go identifier.
func isExportedIdent(name string) bool {
	return name != "" && unicode.IsUpper(rune(name[0]))
}

// goRuntimeVersion returns the current Go version in "M.N" form (e.g. "1.24").
func goRuntimeVersion() string {
	v := strings.TrimPrefix(runtime.Version(), "go")
	parts := strings.SplitN(v, ".", 3)
	if len(parts) >= 2 {
		return parts[0] + "." + parts[1]
	}
	return v
}

// wipeGoProject removes all .go files, go.mod, and go.sum from folderPath.
// Errors are silently ignored — the next SURVEY attempt overwrites anyway.
func wipeGoProject(folderPath string) {
	_ = filepath.WalkDir(folderPath, func(path string, d os.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return nil
		}
		base := filepath.Base(path)
		if strings.HasSuffix(base, ".go") || base == "go.mod" || base == "go.sum" {
			_ = os.Remove(path)
		}
		return nil
	})
}